services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ds_psi
      MYSQL_USER: ds_psi
      MYSQL_PASSWORD: ds_psi
    ports:
      - '3306:3306'
    volumes:
      - ds_psi_mysql:/var/lib/mysql

volumes:
  ds_psi_mysql:
