import { defineQuestionnaire } from '../helpers.js'

/** ASEBA/CBCL 6–18 — itens comportamentais (versão portuguesa). */
export const ASEBA_CBCL_6_18_ITEMS = [
  'Age como crianças mais novas',
  'Bebe álcool sem aprovação dos pais',
  'Discute ou é desafiador',
  'Não tem amigos próximos',
  'Come demasiado',
  'Não come bem',
  'Não partilha com outras crianças',
  'Teimoso, mau humor',
  'Tímido ou reservado',
  'Confunde realidade com fantasia',
  'Destrói as suas coisas',
  'Destrói coisas de outras pessoas',
  'Desobediente em casa',
  'Desobediente na escola',
  'Não come bem (repetido)',
  'Não se sente culpado após comportamento inadequado',
  'Briga muito com irmãos',
  'Frequentemente mal-humorado, infeliz ou deprimido',
  'Gosta de estar com adultos mais do que com crianças',
  'Tem medos',
  'Come demasiado (repetido)',
  'Não quer comer',
  'Constipado ou não usa o lavatório',
  'Culpa os outros dos seus problemas',
  'Guarda segredos que não deveria',
  'Come coisas que não são comida',
  'Tem dificuldades em dormir',
  'Faz coisas que chamam a atenção',
  'Gosta de ser ajudado mais do que outras crianças da sua idade',
  'Grita muito',
  'Esconde-se',
  'É demasiado dependente',
  'Sente-se inútil ou inferior',
  'Mentiroso ou enganador',
  'Bate em outras pessoas',
  'Tem pesadelos',
  'Não gosta de crianças mais novas',
  'Não gosta de crianças mais velhas',
  'Prefere estar com crianças mais novas',
  'Problemas com os olhos',
  'Problemas com os ouvidos',
  'Pega em coisas que não lhe pertencem',
  'Pega em coisas em casa',
  'Pega em coisas na escola',
  'Prefere estar com adultos',
  'Repete certos actos repetidamente',
  'Corre quando não deve',
  'Sexualmente muito activo para a idade',
  'Mostra-se nu ou sem roupa',
  'Fala demasiado sobre sexo',
  'Auto-mutilação ou tentativa de suicídio',
  'Fala demasiado',
  'Fala demasiado sobre sexo (repetido)',
  'Temperamento explosivo',
  'Pensa em sexo demais',
  'Ameaça outras pessoas',
  'Fala demasiado (repetido)',
  'Faz-se de vítima',
  'Muito sensível',
  'Sonâmbulo',
  'Fala demasiado sobre sexo',
  'Teimosia',
  'Temperamento explosivo (repetido)',
  'Pensa em sexo demais (repetido)',
  'Ameaça outras pessoas (repetido)',
  'Faz-se de vítima (repetido)',
  'Muito sensível (repetido)',
  'Sonâmbulo (repetido)',
  'Fala demasiado (repetido)',
  'Temperamento explosivo (repetido)',
  'Pensa em sexo demais (repetido)',
  'Ameaça outras pessoas (repetido)',
  'Faz-se de vítima (repetido)',
  'Muito sensível (repetido)',
  'Sonâmbulo (repetido)',
  'Usa drogas',
  'Vomita',
  'Quer estar com os pais',
  'Retira-se, não interage',
  'Fala demasiado (repetido)',
  'Temperamento explosivo (repetido)',
  'Pensa em sexo demais (repetido)',
  'Ameaça outras pessoas (repetido)',
  'Faz-se de vítima (repetido)',
  'Muito sensível (repetido)',
  'Sonâmbulo (repetido)',
  'Usa drogas (repetido)',
  'Vomita (repetido)',
  'Quer estar com os pais (repetido)',
  'Retira-se, não interage (repetido)',
  'Actividades estranhas',
  'Ideias estranhas',
  'Vê coisas que outras pessoas não veem',
  'Ouve sons ou vozes que outras pessoas não ouvem',
  'Fala de matar-se',
  'Crueldade ou crueldade com animais',
  'Crueldade, intimidação ou crueldade com outros',
  'Prefere estar sozinho',
  'Não se sente culpado',
  'Muito pouco interesse em coisas',
  'Movimentos estranhos',
  'Confusão ou confusão mental',
  'Olha fixamente',
  'Repete palavras ou frases',
  'Rígido',
  'Pensamentos estranhos',
  'Comportamento estranho',
  'Fala de matar-se (repetido)',
  'Crueldade com animais (repetido)',
  'Crueldade com outros (repetido)',
  'Prefere estar sozinho (repetido)',
  'Não se sente culpado (repetido)',
  'Pouco interesse (repetido)',
  'Movimentos estranhos (repetido)',
  'Confusão (repetido)',
  'Olha fixamente (repetido)',
  'Repete palavras (repetido)',
  'Rígido (repetido)',
  'Pensamentos estranhos (repetido)',
  'Comportamento estranho (repetido)',
]

const ASEBA_LABELS = ['Não é verdade', 'Às vezes verdade', 'Muito verdade']

function defineAseba(
  id: string,
  title: string,
  description: string,
  respondent: string,
  items: string[],
) {
  return defineQuestionnaire({
    id,
    title,
    description,
    instructions:
      'Para cada afirmação, indique se é verdadeira sobre a criança/jovem nos últimos 6 meses.',
    respondent,
    responseType: 'frequency0_2',
    responseLabels: ASEBA_LABELS,
    items,
    scoring: {
      type: 'sum_subscales',
      subscales: [{ id: 'total', label: 'Total', itemIds: items.map((_, i) => `q${i + 1}`) }],
    },
  })
}

export const asebaQuestionnaires = [
  defineAseba(
    'cbcl',
    'ASEBA — CBCL (6–18 anos)',
    'Child Behavior Checklist — versão para pais (6–18 anos).',
    'Pais',
    ASEBA_CBCL_6_18_ITEMS,
  ),
  defineAseba(
    'cbcl_18m_5',
    'ASEBA — CBCL (18 meses–5 anos)',
    'Child Behavior Checklist — versão pré-escolar.',
    'Pais',
    ASEBA_CBCL_6_18_ITEMS.slice(0, 99),
  ),
  defineAseba(
    'trf',
    'ASEBA — TRF',
    'Teacher Report Form — versão para professores.',
    'Professores',
    ASEBA_CBCL_6_18_ITEMS,
  ),
  defineAseba(
    'ctrf_18m_5',
    'ASEBA — C-TRF (18 meses–5 anos)',
    'Caregiver-Teacher Report Form — versão pré-escolar.',
    'Educadores',
    ASEBA_CBCL_6_18_ITEMS.slice(0, 99),
  ),
  defineAseba(
    'ysr',
    'ASEBA — YSR',
    'Youth Self Report — autorrelato (11–18 anos).',
    'Jovem',
    ASEBA_CBCL_6_18_ITEMS,
  ),
]
