import { defineQuestionnaire } from '../helpers.js'

const BRIEF_NAF_LABELS = ['Nunca', 'Às vezes', 'Frequentemente']

const BRIEF_PRE_ITEMS = [
  'Reage de forma exagerada a pequenos problemas',
  'Quando lhe são dadas três tarefas, apenas recorda a primeira ou a última.',
  'Não tem consciência de como o seu comportamento afeta ou incomoda os outros',
  'Quando lhe pedem para arrumar, arruma de forma desorganizada/aleatória',
  'Fica incomodado com novas situações',
  'Tem comportamentos explosivos ou de fúria',
  'Tem dificuldade em levar a cabo as ações necessárias para completar tarefas (fazer um puzzle colocando uma peça de cada vez)',
  'Perante um acontecimento engraçado, não consegue parar de rir, mesmo quando todos os outros já pararam',
  'Necessita que lhe digam para iniciar uma atividade, mesmo quando manifesta vontade de a realizar.',
  'Tem dificuldade em adaptar-se a novas pessoas (babysitter, educadora, amigo, cuidador pontual)',
  'Chateia-se muito facilmente.',
  'Tem dificuldade em concentrar-se nos seus jogos, puzzles e/ou outras atividades',
  'Tem de ter supervisão apertada, mais do que os seus pares',
  'Quando lhe pedem que vá buscar alguma coisa, esquece-se do que lhe foi pedido.',
  'Fica incomodado quando há mudança de planos ou rotinas',
  'Tem comportamentos explosivos por pequenos motivos.',
  'Repete os mesmos disparates vezes sem conta, mesmo depois de ser ajudado ou corrigido',
  'Comporta-se de forma mais selvagem ou apalhaçada que os outros quando em grupo',
  'Não encontra roupa, sapatos, brinquedos, livros, mesmo quando lhe são dadas instruções específicas',
  'Demora muito tempo para se sentir confortável num novo local ou situação',
  'Muda de humor frequentemente',
  'Faz muitos disparates mesmo nas tarefas que já sabe fazer',
  'É irrequieto, agitado',
  'Tem dificuldade em seguir as rotinas pré-definidas para dormir, comer, brincar',
  'Fica incomodado com ruídos altos, luzes brilhantes ou determinados cheiros',
  'Pequenos eventos despoletam grandes reações',
  'Tem problemas em realizar atividades ou tarefas que tenham mais que uma ação/etapa',
  'É impulsivo',
  'Tem dificuldade em pensar de forma diferente para resolver um problema ou completar uma atividade, mesmo quando a sua abordagem não resulta',
  'Fica perturbado com mudanças no ambiente (mobília nova/mudar mobília de local, roupa nova)',
  'Episódios de fúria ou choro são intensos, mas curtos.',
  'Necessita de ajuda de um adulto para se manter numa tarefa',
  'Não se apercebe quando o seu comportamento causa reações negativas',
  'Deixa tudo desarrumado mesmo depois de ser dada instrução para arrumar',
  'Tem problemas em mudar de atividades',
  'Tem reações mais fortes às situações que as outras crianças da sua idade',
  'Esquece-se do que estava a fazer a meio de uma atividade',
  'Não se apercebe que algumas ações incomodam os outros.',
  'Prende-se em pequenos detalhes de uma tarefa ou situação e não consegue perceber a sua ideia global',
  'Tem dificuldades em participar em eventos sociais pouco familiares',
  'Fica facilmente alarmado ou excitado com as suas atividades diárias',
  'Tem problemas em concluir tarefas (puzzles, jogos faz de conta)',
  'Perde o controlo mais do que os seus pares',
  'Não consegue encontrar objetos no seu quarto ou área de brincar, mesmo quando lhe são dadas instruções específicas',
  'Resiste a mudanças de rotina, comidas, lugares, etc.',
  'Depois de ter um problema, mostra-se desapontado durante muito tempo.',
  'Não consegue manter o mesmo tópico durante uma conversa',
  'Fala muito alto ou brinca de forma muito ruidosa',
  'Não completa tarefas mesmo quando lhe são dadas algumas direções',
  'Fica alarmado ou excitado em situações de maior confusão',
  'Tem problemas em começar atividades ou tarefas mesmo depois de ser dada uma instrução',
  'Comporta-se de forma demasiado selvagem ou fora do controlo',
  'Não se esforça para realizar as atividades de acordo com as suas capacidades',
  'Tem problemas em «pôr um travão» nas suas ações, mesmo quando lhe pedem para o fazer',
  'É incapaz de concluir a descrição de um evento, pessoa ou história',
  'Completa tarefas ou atividades rapidamente (de forma desleixada)',
  'Não tem consciência se faz bem ou mal',
  'É facilmente distraído durante a realização de uma atividade',
  'Tem dificuldade em lembrar-se de certas coisas, mesmo depois de um curto período de tempo',
  'Torna-se demasiado «apalhaçado»',
  'Tem um tempo curto de atenção',
  'Brinca de forma descuidada ou imprudente em situações onde se pode magoar',
  'Não tem consciência se o seu desempenho em determinada tarefa foi bom ou mau',
]

const BRIEF_SCHOOL_ITEMS = [
  'Reage de forma exagerada a pequenos problemas.',
  'Quando lhe são dadas três tarefas, apenas recorda a primeira ou a última.',
  'Não inicia as tarefas sozinho.',
  'Deixa o local onde brinca desarrumado.',
  'Apresenta resistência ou dificuldade em aceitar diferentes formas de resolver um problema.',
  'Fica incomodado com novas situações.',
  'Tem comportamentos explosivos ou de fúria.',
  'Tenta a mesma abordagem a um problema repetidamente, mesmo quando esta não resulta.',
  'Tem um tempo de atenção curto.',
  'Necessita que lhe digam para iniciar uma atividade, mesmo quando manifesta vontade de a realizar.',
  'Não traz para casa trabalhos escolares, fichas de trabalho, materiais, etc.',
  'Fica incomodado com alterações de planos.',
  'Fica perturbado com mudança de professor ou aula.',
  'Não verifica erros nos trabalhos.',
  'Tem boas ideias, mas não consegue passá-las para o papel.',
  'Tem dificuldade em ter ideias para o que fazer nas brincadeiras ou nos tempos livres.',
  'Tem problemas em concentrar-se nas tarefas, nos trabalhos escolares, etc.',
  'Não relaciona a realização dos trabalhos de casa diários com as suas notas.',
  'Distrai-se facilmente com barulhos, movimento ou estímulos visuais.',
  'Chora facilmente.',
  'Comete erros por descuido.',
  'Esquece-se de entregar os trabalhos de casa, mesmo quando estão feitos.',
  'Resiste a mudanças de rotina, comidas, lugares, etc.',
  'Tem problemas em realizar atividades ou tarefas que tenham mais que uma ação/etapa.',
  'Tem comportamentos explosivos por pequenos motivos.',
  'Muda de humor frequentemente.',
  'Necessita de ajuda do adulto para se manter numa tarefa.',
  'Prende-se em detalhes e perde a ideia global.',
  'Mantém o quarto desarrumado.',
  'Tem dificuldades em habituar-se a novas situações (aulas, grupos, amigos).',
  'Tem uma caligrafia pobre.',
  'Esquece-se do que estava a fazer.',
  'Quando lhe pedem que vá buscar alguma coisa, esquece-se do que lhe foi pedido.',
  'Não tem consciência de como o seu comportamento afeta ou incomoda os outros.',
  'Tem boas ideias, mas não as realiza (falta de seguimento).',
  'Fica alarmado com grandes trabalhos.',
  'Tem problemas em concluir tarefas (atividades, trabalhos de casa)',
  'Comporta-se de forma mais selvagem ou apalhaçada que os outros quando em grupo.',
  'Pensa demasiado sobre o mesmo assunto.',
  'Subestima o tempo necessário para terminar as tarefas.',
  'Interrompe os outros.',
  'Não se apercebe quando o seu comportamento causa reações negativas.',
  'Levanta-se do lugar quando não deve.',
  'Perde o controlo, mais do que os amigos.',
  'Tem reações às situações mais fortes que as outras crianças.',
  'Está até à última para iniciar os trabalhos ou tarefas.',
  'Tem problemas em começar trabalhos de casa ou atividades.',
  'Tem problemas em organizar atividades com amigos.',
  'Fala abruptamente, sem pensar.',
  'O humor é facilmente influenciado pela situação.',
  'Não planeia com antecedência os trabalhos escolares.',
  'Tem fraco reconhecimento das suas capacidades e dificuldades.',
  'Os trabalhos escritos têm uma organização pobre.',
  'Comporta-se de forma demasiado selvagem ou fora de controlo.',
  'Tem problemas em «pôr um travão» nas suas ações.',
  'Mete-se em problemas, quando não é supervisionado por um adulto.',
  'Tem problemas em lembrar-se das coisas, mesmo por alguns minutos.',
  'Tem problemas em levar a cabo as ações necessárias para atingir um objetivo.',
  'Torna-se demasiado «apalhaçado».',
  'É desleixado nos trabalhos.',
  'Não toma a iniciativa.',
  'Episódios de fúria ou choro são intensos, mas curtos.',
  'Não se apercebe que algumas ações incomodam os outros.',
  'Pequenos eventos despoletam grandes reações.',
  'Fala quando não deve.',
  'Queixa-se que não tem nada para fazer.',
  'Não consegue encontrar as coisas no quarto ou na secretária.',
  'Deixa um rasto de pertences onde quer que vá.',
  'Deixa as coisas desarrumadas que os outros têm de arrumar.',
  'Chateia-se muito facilmente.',
  'Deita-se no sofá ou pela casa muitas vezes.',
  'Tem um roupeiro desarrumado.',
  'Tem problemas em esperar pela vez.',
  'Perde a lancheira, o dinheiro do almoço, trabalhos de casa, recados, etc.',
  'Não encontra roupas, óculos, sapatos, brinquedos, livros, lápis, etc.',
  'Maus resultados nos testes mesmo quando sabe as respostas corretas.',
  'Não termina projetos a longo termo.',
  'Tem de ter supervisão apertada.',
  'Não pensa antes de fazer/agir.',
  'Tem problemas em passar de uma atividade para outra.',
  'É irrequieto.',
  'É impulsivo.',
  'Não consegue manter o mesmo tópico durante uma conversa.',
  '«Fica preso» num tópico ou atividade.',
  'Diz a mesma coisa uma e outra vez.',
  'Tem problemas em realizar a rotina matinal e preparar-se para a escola.',
]

function briefScoring(count: number) {
  return {
    type: 'sum_subscales' as const,
    subscales: [
      {
        id: 'total',
        label: 'Total BRIEF',
        itemIds: Array.from({ length: count }, (_, i) => `q${i + 1}`),
      },
    ],
  }
}

export const briefQuestionnaires = [
  defineQuestionnaire({
    id: 'brief_pre_escolar',
    title: 'BRIEF — Idade Pré-escolar',
    description: 'Avaliação das funções executivas (versão pré-escolar).',
    instructions:
      'Indique se cada comportamento foi problemático nos últimos 6 meses: N = Nunca, AV = Às vezes, F = Frequentemente.',
    respondent: 'Pais ou educadores',
    responseType: 'frequency0_2',
    responseLabels: BRIEF_NAF_LABELS,
    items: BRIEF_PRE_ITEMS,
    scoring: briefScoring(BRIEF_PRE_ITEMS.length),
  }),
  defineQuestionnaire({
    id: 'brief_idade_escolar_pais',
    title: 'BRIEF — Idade Escolar (Pais)',
    description: 'Avaliação das funções executivas — versão para pais (idade escolar).',
    instructions:
      'Indique se cada comportamento foi problemático nos últimos 6 meses: N = Nunca, AV = Às vezes, F = Frequentemente.',
    respondent: 'Pais',
    responseType: 'frequency0_2',
    responseLabels: BRIEF_NAF_LABELS,
    items: BRIEF_SCHOOL_ITEMS,
    scoring: briefScoring(BRIEF_SCHOOL_ITEMS.length),
  }),
]
