import { defineQuestionnaire } from '../helpers.js'

const IEP_ITEMS = [
  'Quando o meu filho (a) sai, conta espontaneamente onde vai.',
  'Ensino o meu filho (a) a devolver objectos ou dinheiro que não lhe pertencem.',
  'Quando o meu filho (a) faz algo errado, a punição que aplico é mais severa dependendo do meu humor.',
  'O meu trabalho interfere na atenção que dou ao meu filho (a).',
  'Ameaço que vou bater ou castigar e depois não faço nada.',
  'Critico qualquer coisa que o meu filho (a) faça, como o quarto estar desarrumado ou estar despenteado.',
  'Bato com o cinto e outros objectos no meu filho (a).',
  'Pergunto como foi o seu dia na escola e ouço-o atentamente.',
  'Se o meu filho (a) copiar num teste, explico-lhe que é melhor ter uma nota baixa do que enganar o professor ou a si mesmo.',
  'Quando estou alegre, não me importo com as coisas erradas que o meu filho (a) faça.',
  'O meu filho (a) sente muitas dificuldades em contar-me os seus problemas, pois sou uma pessoa muito ocupada.',
  'Quando castigo o meu filho (a) e ele (a) me pede para sair do castigo, após alguma insistência permito que o faça.',
  'Quando o meu filho (a) sai, telefono para falar com ele (a) muitas vezes.',
  'O meu filho (a) tem muito medo de apanhar de mim.',
  'Quando o meu filho (a) está triste ou aborrecido (a), interesso-me em ajudá-lo (a) a resolver os seus problemas.',
  'Se o meu filho (a) estragar alguma coisa de alguém, ensino-o (a) a contar o que fez e a pedir desculpas.',
  'Castigo-o (a) quando estou nervoso (a); assim que passa a raiva, peço desculpas.',
  'O meu filho (a) fica sozinho (a) em casa a maior parte do tempo.',
  'Se, durante uma briga, o meu filho (a) grita comigo, então eu deixo-o (a) em paz.',
  'Controlo com quem o meu filho fala ou sai.',
  'O meu filho (a) fica magoado (a) fisicamente quando bato nele (a).',
  'Mesmo quando estou ocupado (a) ou a viajar, telefono para saber como ele (a) está.',
  'Aconselho o meu filho (a) a ler livros, revistas ou a ver programas de televisão que mostrem os efeitos negativos do consumo de drogas.',
  'Quando estou nervoso (a), acabo por descarregar no (a) meu filho (a).',
  'O meu filho (a) sente que não lhe dou atenção.',
  'Quando mando o meu filho (a) estudar, arrumar o quarto ou voltar para casa e ele (a) não obedece, eu não dou muita importância.',
  'Especialmente nas horas das refeições, aborreço-me e chateio-me com o meu filho (a).',
  'O meu filho (a) sente ódio de mim quando lhe bato.',
  'Após uma festa quero saber se o meu filho (a) se divertiu.',
  'Converso com o meu filho (a) sobre o que é certo ou errado no comportamento das personagens dos filmes e dos programas de televisão.',
  'Sou mal-humorado (a) com o meu filho.',
  'Não sei dizer do que o meu filho (a) gosta.',
  'Aviso o meu filho (a) que não lhe dou presentes se ele (a) não estudar, mas, na hora H, fico com pena e dou-lhe o presente.',
  'Se o meu filho (a) vai a uma festa, apenas quero saber se ele (a) bebeu, se fumou, se estava com más companhias.',
  'Sou agressivo (a) com o meu filho (a).',
  'Estabeleço regras (o que pode e o que não pode ser feito) e explico as razões sem discussão.',
  'Converso sobre o futuro trabalho ou profissão do meu filho (a), mostrando-lhe os pontos positivos e negativos das suas escolhas.',
  'Quando estou mal-humorado (a), não deixo o meu filho (a) sair com os amigos.',
  'Ignoro os problemas do meu filho (a).',
  'Quando o meu filho (a) fica muito nervoso (a) numa discussão ou briga, ele (a) percebe que fico amedrontado.',
  'Se o meu filho (a) estiver aborrecido (a), insisto para que me conte o que aconteceu, mesmo que ele (a) não queira contar.',
  'Sou violento (a) com o meu filho (a).',
]

export const iepQuestionnaire = defineQuestionnaire({
  id: 'iep',
  title: 'Inventário de Estilos Parentais (IEP)',
  description: 'Práticas educativas maternas e paternas — auto-aplicação.',
  instructions:
    'Indique a frequência com que age nas situações descritas: 0 = Nunca, 1 = Às vezes, 2 = Sempre.',
  respondent: 'Pais',
  responseType: 'frequency0_2',
  responseLabels: ['Nunca', 'Às vezes', 'Sempre'],
  items: IEP_ITEMS,
  scoring: { type: 'iep' },
})
