import { defineQuestionnaire } from '../helpers.js'

const OBQ44_ITEMS = [
  'Eu frequentemente penso que as coisas ao meu redor são perigosas.',
  'Se eu não tiver absoluta certeza de alguma coisa, com certeza eu vou errar.',
  'As coisas deveriam ser perfeitas de acordo com as minhas próprias normas/regras.',
  'A fim de ser uma pessoa de valor (digna), eu devo ser perfeito em tudo que faço.',
  'Quando eu percebo que tenho chance, eu devo agir para evitar que coisas ruins aconteçam.',
  'Mesmo que algo ruim tenha pouca probabilidade de ocorrer, devo tentar prevenir a qualquer custo.',
  'Para mim, ter vontade de fazer algo ruim é o mesmo que fazê-lo.',
  'Se eu não agir quando sentir o perigo, serei responsável por quaisquer consequências.',
  'Se eu não puder fazer algo perfeito, eu não deveria fazer nada.',
  'Eu devo dar o máximo de mim o tempo todo.',
  'É muito importante para mim considerar todas as alternativas possíveis de uma situação.',
  'Mesmo tendo pequenos erros, significa que o trabalho não está completo.',
  'Se eu tiver pensamentos ou impulsos agressivos sobre as pessoas importantes para mim, isto significa que, secretamente, eu quero machucá-las.',
  'Devo sempre ter certeza das minhas decisões.',
  'Em todas as atividades diárias, falhar em prevenir os danos é tão ruim quanto provocá-los.',
  'Evitar problemas graves (por exemplo, doença ou acidentes) exige constante esforço da minha parte.',
  'Para mim, não prevenir dano é tão ruim quanto causá-lo.',
  'Eu deveria ficar triste se cometer um erro.',
  'Eu devo ter certeza que os outros estejam protegidos de quaisquer consequências negativas das minhas decisões ou atos.',
  'Para mim, as coisas não estão corretas se não estiverem perfeitas.',
  'Ter pensamentos horríveis significa que eu sou uma pessoa má.',
  'Se eu não tomar cuidados extras (além dos usuais), eu tenho mais chance do que os outros de sofrer ou causar um sério acidente.',
  'Para eu me sentir seguro, tenho que estar tão preparado quanto for possível para qualquer coisa que possa dar errado.',
  'Eu não deveria ter pensamentos bizarros ou revoltantes.',
  'Para mim, cometer um erro é tão ruim quanto falhar totalmente.',
  'É essencial que tudo seja bem claro (compreensível), mesmo nos mínimos detalhes.',
  'Ter pensamentos pecaminosos é tão ruim quanto cometê-los.',
  'Eu deveria ser capaz de livrar minha mente de pensamentos indesejáveis.',
  'Eu tenho mais probabilidade do que as outras pessoas, de acidentalmente, causar danos a mim mesmo ou aos outros.',
  'Ter maus pensamentos significa que eu sou estranho ou anormal.',
  'Eu devo ser o melhor nas coisas que são importantes para mim.',
  'Ter um pensamento ou imagem sexual indesejados significa que eu realmente quero realizá-los.',
  'Se minhas ações pudessem ter um efeito, mesmo pequeno, sobre alguma possível desgraça, eu seria o responsável pelo ocorrido.',
  'Mesmo quando eu sou cuidadoso, frequentemente penso que coisas ruins irão ocorrer.',
  'Ter pensamentos intrusivos (que involuntariamente invadem a minha mente) significa que eu estou fora de controle.',
  'Eventos prejudiciais poderão acontecer, a menos que eu seja muito cuidadoso.',
  'Eu devo trabalhar em algo até que fique perfeito.',
  'Ter pensamentos violentos significa que eu vou perder o controle e me tornarei violento.',
  'Para mim, não conseguir evitar um desastre é tão ruim quanto causá-lo.',
  'Se eu não fizer um trabalho perfeito, as pessoas não me respeitarão.',
  'Mesmo experiências comuns (do dia a dia) na minha vida, são cheias de risco.',
  'Ter um mau pensamento equivale moralmente a praticar uma má ação.',
  'Não importa o que eu faça, nunca será bom o suficiente.',
  'Se eu não controlar meus pensamentos, eu serei punido.',
]

export const obq44Questionnaire = defineQuestionnaire({
  id: 'obq_44',
  title: 'OBQ-44',
  description: 'Obsessional Beliefs Questionnaire — inventário de crenças obsessivas.',
  instructions:
    'Leia cada afirmativa e indique o quanto concorda ou discorda, numa escala de 1 (discordo totalmente) a 7 (concordo totalmente).',
  respondent: 'Adolescente ou adulto',
  responseType: 'likert7',
  items: OBQ44_ITEMS,
  scoring: { type: 'obq44' },
})
