import { defineQuestionnaire } from '../helpers.js'

const RCMAS_ITEMS = [
  'Tenho dificuldade em decidir-me.',
  'Fico nervoso(a) quando as coisas não me correm bem.',
  'Parece que as outras pessoas fazem as coisas mais facilmente do que eu.',
  'Gosto de todas as pessoas que conheço.',
  'Tenho frequentemente dificuldades em respirar.',
  'Ando muitas vezes preocupado(a).',
  'Tenho medo de muitas coisas.',
  'Sou sempre amável.',
  'Fico facilmente magoado(a) ou furioso(a).',
  'Preocupo-me com o que os meus pais me irão dizer.',
  'Sinto que os outros não gostam da maneira como eu faço as coisas.',
  'Tenho sempre boas maneiras.',
  'Tenho dificuldade em adormecer à noite.',
  'Preocupo-me com o que as outras pessoas pensam de mim.',
  'Sinto-me só mesmo quando há pessoas comigo.',
  'Comporto-me sempre bem.',
  'Sinto-me enjoado(a) muitas vezes.',
  'Fico facilmente magoado(a).',
  'Sinto as minhas mãos suadas.',
  'Sou sempre bem educado(a) para com os outros.',
  'Canso-me muito.',
  'Preocupo-me com o que vai acontecer.',
  'As outras pessoas são mais felizes do que eu.',
  'Digo sempre a verdade.',
  'Tenho maus sonhos.',
  'Fico facilmente magoado(a) quando ando chateado(a).',
  'Sinto que alguém me vai dizer que ando a fazer mal as coisas.',
  'Nunca me irrito.',
  'Às vezes acordo assustado(a).',
  'Fico preocupado(a) quando à noite vou para a cama.',
  'Tenho dificuldade em concentrar-me no meu trabalho escolar.',
  'Nunca digo coisas que não deveria dizer.',
  'Mexo-me muito na minha cadeira.',
  'Sou nervoso(a).',
  'Há muita gente que é contra mim.',
  'Nunca minto.',
  'Preocupo-me muitas vezes com que me vá acontecer alguma coisa má.',
]

export const rcmasQuestionnaire = defineQuestionnaire({
  id: 'rcmas',
  title: 'RCMAS',
  description:
    'Escala Revista de Ansiedade Manifesta para Crianças (RCMAS; Reynolds & Richmond, 1978; versão portuguesa de Fonseca, 1992).',
  instructions:
    'Segue-se uma lista de frases a descrever como às vezes as pessoas se sentem. Marque Sim ou Não conforme concorda ou não com o que em cada frase se afirma.',
  respondent: 'Criança/jovem',
  responseType: 'yes_no',
  items: RCMAS_ITEMS,
  scoring: { type: 'rcmas' },
})
