import { defineQuestionnaire, itemsFromTexts, sdqScoring, SDQ_4_17_ITEMS } from '../helpers.js'

const SDQ_INSTRUCTIONS =
  'Para cada frase, marque uma das opções conforme o comportamento nos últimos seis meses.'

const SDQ_P_3_4_ITEMS = [
  'É atencioso/a com os sentimentos dos outros',
  'É inquieto/a, não consegue ficar parado/a durante muito tempo',
  'Queixa-se frequentemente de dores de cabeça, barriga ou enjoo',
  'Partilha com outras crianças (doces, brinquedos, lápis, etc.)',
  'Tem frequentemente acessos de raiva ou birras',
  'Prefere brincar sozinho/a',
  'Geralmente obedece, faz o que os adultos pedem',
  'Tem muitas preocupações, parece preocupado/a',
  'É prestável se alguém está magoado, aborrecido ou doente',
  'Está sempre a mexer-se',
  'Tem pelo menos um bom amigo/uma boa amiga',
  'Briga ou intimida outras crianças',
  'É muitas vezes infeliz, desanimado/a ou choroso/a',
  'Em geral é querido/a por outras crianças',
  'Distrai-se facilmente, parece sonhador/a',
  'É receoso/a ou tímido/a com pessoas novas',
  'É gentil com crianças mais novas',
  'Mente ou engana',
  'É alvo de provocações ou intimidação',
  'Oferece-se para ajudar (pais, professores, outras crianças)',
  'Pensa antes de agir',
  'Rouba em casa, na escola ou noutros sítios',
  'Dá-se melhor com adultos do que com crianças',
  'Tem muitos medos, assusta-se facilmente',
  'Termina o que começa, tem boa atenção',
]

const SDQ_PROF_ITEMS = [
  'Considera os sentimentos dos outros',
  'Inquieto/a, não consegue ficar parado/a',
  'Queixa-se frequentemente de dores de cabeça, barriga ou enjoo',
  'Partilha com outras crianças',
  'Tem frequentemente acessos de raiva ou birras',
  'Prefere brincar sozinho/a',
  'Geralmente obedece',
  'Tem muitas preocupações',
  'É prestável se alguém está magoado ou doente',
  'Está sempre a mexer-se',
  'Tem pelo menos um bom amigo/uma boa amiga',
  'Briga ou intimida outras crianças',
  'É muitas vezes infeliz ou desanimado/a',
  'É geralmente querido/a pelos colegas',
  'Distrai-se facilmente',
  'É receoso/a ou ansioso/a em situações novas',
  'É gentil com crianças mais novas',
  'Mente ou engana',
  'É alvo de provocações ou intimidação',
  'Oferece-se para ajudar',
  'Pensa antes de agir',
  'Rouba',
  'Dá-se melhor com adultos do que com crianças',
  'Tem muitos medos',
  'Termina o que começa, tem boa atenção',
]

export const sdqQuestionnaires = [
  defineQuestionnaire({
    id: 'sdq_p_3_4',
    title: 'SDQ-P (3–4 anos)',
    description: 'Questionário de Capacidades e Dificuldades para pais/educadores de crianças dos 3 aos 4 anos.',
    instructions: SDQ_INSTRUCTIONS,
    respondent: 'Pais ou educadores',
    responseType: 'likert3_sdq',
    items: SDQ_P_3_4_ITEMS,
    scoring: sdqScoring(),
  }),
  defineQuestionnaire({
    id: 'sdq_4_17',
    title: 'SDQ (4–17 anos)',
    description: 'Questionário de Capacidades e Dificuldades para pais de crianças e jovens dos 4 aos 17 anos.',
    instructions: SDQ_INSTRUCTIONS,
    respondent: 'Pais',
    responseType: 'likert3_sdq',
    items: SDQ_4_17_ITEMS,
    scoring: sdqScoring(),
  }),
  defineQuestionnaire({
    id: 'sdq_prof',
    title: 'SDQ — Professores',
    description: 'Versão para professores do Questionário de Capacidades e Dificuldades.',
    instructions: SDQ_INSTRUCTIONS,
    respondent: 'Professores',
    responseType: 'likert3_sdq',
    items: SDQ_PROF_ITEMS,
    scoring: sdqScoring(),
  }),
]
