-- Volume VII — checklists clínicas DC:0–5 (terapeuta)
INSERT INTO `picca_modules` (`id`, `volume`, `module_number`, `sort_order`, `title`, `description`, `therapist_only`, `active`, `updated_at`) VALUES
('picca-vol7-mod1', 7, 1, 1, 'Perturbação do Espetro do Autismo', 'Checklist clínica DC:0–5 com indicadores Sim/Não/Não observado.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod2', 7, 2, 2, 'Perturbação do Espetro do Autismo Atípica Precoce', 'Checklist clínica DC:0–5 com indicadores Sim/Não/Não observado.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod3', 7, 3, 3, 'Perturbação de Hiperatividade e Défice de Atenção – PHDA', 'Checklist clínica DC:0–5 com indicadores Sim/Não/Não observado.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod4', 7, 4, 4, 'Perturbação de Hiperatividade da Primeira Infância', 'Checklist clínica DC:0–5 com indicadores Sim/Não/Não observado.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod5', 7, 5, 5, 'Atraso Global do Desenvolvimento', 'Checklist clínica DC:0–5 com indicadores Sim/Não/Não observado.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod6', 7, 6, 6, 'Perturbação do Desenvolvimento da Linguagem', 'Checklist clínica DC:0–5 com indicadores Sim/Não/Não observado.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod7', 7, 7, 7, 'Perturbação de Hiper-reatividade Sensorial', 'Checklist clínica DC:0–5 com indicadores Sim/Não/Não observado.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod8', 7, 8, 8, 'Perturbação de Hipo-reatividade Sensorial', 'Checklist clínica DC:0–5 com indicadores Sim/Não/Não observado.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod9', 7, 9, 9, 'Outra Perturbação do Processamento Sensorial', 'Checklist clínica DC:0–5 com indicadores Sim/Não/Não observado.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod10', 7, 10, 10, 'Perturbação de Ansiedade de Separação', 'Checklist clínica DC:0–5 — perturbações de ansiedade.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod11', 7, 11, 11, 'Perturbação de Ansiedade Social', 'Checklist clínica DC:0–5 — perturbações de ansiedade.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod12', 7, 12, 12, 'Perturbação de Ansiedade Generalizada', 'Checklist clínica DC:0–5 — perturbações de ansiedade.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod13', 7, 13, 13, 'Mutismo Seletivo', 'Checklist clínica DC:0–5 — perturbações de ansiedade.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod14', 7, 14, 14, 'Perturbação de Inibição perante a Novidade', 'Checklist clínica DC:0–5 — perturbações de ansiedade.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod15', 7, 15, 15, 'Outra Perturbação de Ansiedade da Primeira Infância', 'Checklist clínica DC:0–5 — perturbações de ansiedade.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod16', 7, 16, 16, 'Perturbação do Início do Sono', 'Checklist clínica DC:0–5 — sono, alimentação e choro.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod17', 7, 17, 17, 'Perturbação dos Despertares Noturnos', 'Checklist clínica DC:0–5 — sono, alimentação e choro.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod18', 7, 18, 18, 'Perturbação Parcial do Despertar', 'Checklist clínica DC:0–5 — sono, alimentação e choro.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod19', 7, 19, 19, 'Perturbação de Pesadelos da Primeira Infância', 'Checklist clínica DC:0–5 — sono, alimentação e choro.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod20', 7, 20, 20, 'Perturbação de Subalimentação', 'Checklist clínica DC:0–5 — sono, alimentação e choro.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod21', 7, 21, 21, 'Perturbação de Sobrealimentação', 'Checklist clínica DC:0–5 — sono, alimentação e choro.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod22', 7, 22, 22, 'Perturbação Alimentar Atípica', 'Checklist clínica DC:0–5 — sono, alimentação e choro.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod23', 7, 23, 23, 'Pica', 'Checklist clínica DC:0–5 — sono, alimentação e choro.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod24', 7, 24, 24, 'Ruminação', 'Checklist clínica DC:0–5 — sono, alimentação e choro.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod25', 7, 25, 25, 'Perturbação do Choro Excessivo', 'Checklist clínica DC:0–5 — sono, alimentação e choro.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod26', 7, 26, 26, 'Perturbação Depressiva da Primeira Infância', 'Checklist clínica DC:0–5 — perturbações do humor.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod27', 7, 27, 27, 'Perturbação Mista da Expressão Emocional', 'Checklist clínica DC:0–5 — perturbações do humor.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod28', 7, 28, 28, 'Outra Perturbação do Humor da Primeira Infância', 'Checklist clínica DC:0–5 — perturbações do humor.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod29', 7, 29, 29, 'Irritabilidade Persistente', 'Checklist clínica DC:0–5 — perturbações do humor.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod30', 7, 30, 30, 'Perturbação Obsessivo-compulsiva', 'Checklist clínica DC:0–5 — POC e perturbações relacionadas.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod31', 7, 31, 31, 'Comportamentos Repetitivos Centrados no Corpo', 'Checklist clínica DC:0–5 — POC e perturbações relacionadas.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod32', 7, 32, 32, 'Outra Perturbação Obsessivo-compulsiva e Relacionada', 'Checklist clínica DC:0–5 — POC e perturbações relacionadas.', true, true, CURRENT_TIMESTAMP(3)),
('picca-vol7-mod33', 7, 33, 33, 'Checklist Clínica de Observação Sistemática', 'Observação sistemática de domínios clínicos (Manual Clínico PICCA).', true, true, CURRENT_TIMESTAMP(3))
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `description` = VALUES(`description`),
  `therapist_only` = VALUES(`therapist_only`),
  `active` = VALUES(`active`),
  `updated_at` = CURRENT_TIMESTAMP(3);
