// Auto-generated from scripts/picca_vol7_manual_extract.txt

export type Vol7ManualChapter = { number: number; title: string; body: string }

export const PICCA_VOL7_MANUAL_TITLE = "Manual Clínico de Diagnóstico em Idade Pré-Escolar (0–5 anos)"

export const PICCA_VOL7_MANUAL_PREFACE = "Prefácio\nA infância representa um período de extraordinária plasticidade cerebral, durante o qual o\ndesenvolvimento resulta da interação contínua entre fatores biológicos, psicológicos, familiares e\nambientais. A identificação precoce de alterações do desenvolvimento constitui um dos pilares da\nintervenção clínica, permitindo reduzir o impacto funcional das dificuldades e potenciar trajetórias\ndesenvolvimentais mais adaptativas.\nO sistema DC:0–5™ introduziu uma abordagem especificamente direcionada às crianças dos 0 aos 5\nanos, valorizando uma perspetiva desenvolvimental, relacional, cultural e contextual através de um\nmodelo multiaxial. Este manual não reproduz os critérios oficiais do DC:0–5™, mas inspira-se na sua\nfilosofia clínica para apresentar um guia prático destinado à avaliação psicológica e à formulação clínica\nem idade pré-escolar.\nÍndice\nIntrodução ao desenvolvimento infantil\nDesenvolvimento típico dos 0 aos 5 anos\nBases neurobiológicas do desenvolvimento\nDesenvolvimento emocional\nDesenvolvimento cognitivo\nDesenvolvimento da linguagem\nDesenvolvimento motor\nDesenvolvimento social\nFunções executivas\nAutorregulação\nProcessamento sensorial\nVinculação\nFatores de risco e fatores de proteção\n1.\n2.\n3.\n4.\n5.\n6.\n7.\n8.\n9.\n10.\n11.\n12.\n13.\n\n\nSinais de alerta (Red Flags)\nFormulação clínica\nAvaliação multidisciplinar\nInstrumentos de avaliação\nChecklists clínicas"

export const PICCA_VOL7_MANUAL_CHAPTERS: Vol7ManualChapter[] = [
  { number: 1, title: "Introdução ao Desenvolvimento Infantil", body: "O desenvolvimento infantil\nO desenvolvimento infantil corresponde a um processo contínuo de aquisição de competências que\nresulta da interação dinâmica entre fatores genéticos, neurobiológicos, ambientais e relacionais.\nNenhuma competência surge de forma isolada. Cada aquisição influencia as restantes áreas do\ndesenvolvimento.\nAs principais áreas incluem:\nDesenvolvimento motor\nDesenvolvimento cognitivo\nLinguagem\nComunicação\nDesenvolvimento emocional\nCompetências sociais\nAutonomia\nProcessamento sensorial\nFunções executivas\nPrincípios fundamentais\nO desenvolvimento caracteriza-se por:\ncontinuidade;\nprogressão sequencial;\nvariabilidade individual;\ninfluência do ambiente;\nelevada plasticidade cerebral nos primeiros anos;\ndependência da qualidade das relações precoces.\n14.\n15.\n16.\n17.\n18.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nPorque é importante avaliar cedo?\nUma avaliação precoce permite:\nidentificar dificuldades antes da entrada no ensino obrigatório;\ncompreender fatores de risco e de proteção;\norientar a intervenção terapêutica;\napoiar a família;\napoiar a escola;\ndiminuir o impacto funcional das dificuldades." },
  { number: 2, title: "Desenvolvimento Típico", body: "Desenvolvimento entre o nascimento e os 6 meses\nComunicação\nreage à voz humana;\nsorri socialmente;\nvocaliza;\ninicia contacto ocular.\nMotricidade\ncontrolo progressivo da cabeça;\nleva as mãos à linha média;\ninicia preensão voluntária.\nCognição\nacompanha objetos;\nreconhece cuidadores;\ndemonstra curiosidade visual.\nDesenvolvimento emocional\ndiferencia estados emocionais;\nacalma com figuras de vinculação;\ninicia reciprocidade social.\n6–12 meses\nEspera-se:\ngatinhar;\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nresponder ao nome;\nbrincar de causa-efeito;\nprocurar objetos escondidos;\nbalbucio variado;\nansiedade perante estranhos.\n12–24 meses\nEspera-se:\nmarcha autónoma;\nprimeiras palavras;\ninício da brincadeira funcional;\nimitação;\naumento da autonomia;\ncompreensão de ordens simples.\n24–36 meses\nEspera-se:\nfrases simples;\njogo simbólico;\nmaior autonomia;\ninício do controlo dos esfíncteres;\nidentificação de emoções básicas;\nbrincadeira paralela.\n3 anos\nCompetências esperadas:\nLinguagem\nfrases completas;\ncompreensão adequada;\nnarrativa simples.\nCognição\nclassificação simples;\nresolução de pequenos problemas;\nmemória funcional.\nSocialização\nbrincadeira cooperativa inicial;\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\npartilha;\nespera pela vez.\nMotricidade\nsobe escadas alternando pés;\nsalta;\ndesenha círculo.\n4 anos\nEspera-se:\nlinguagem inteligível;\njogo imaginativo elaborado;\ninício da teoria da mente;\nmaior flexibilidade cognitiva;\nmelhor controlo inibitório.\n5 anos\nEspera-se:\npreparação para aprendizagem formal;\natenção sustentada superior;\nmaior autorregulação;\nautonomia nas atividades diárias;\ncompetências pré-académicas consolidadas." },
  { number: 3, title: "Bases Neurobiológicas", body: "O desenvolvimento cerebral precoce caracteriza-se por:\nintensa sinaptogénese;\nmielinização progressiva;\npoda sináptica;\nelevada plasticidade;\ninfluência determinante da experiência.\nÁreas particularmente relevantes:\ncórtex pré-frontal;\nsistema límbico;\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\ncerebelo;\ncorpo caloso;\nredes de atenção;\nredes executivas." },
  { number: 4, title: "Desenvolvimento Emocional", body: "Principais competências:\nidentificação emocional;\nexpressão emocional;\nregulação emocional;\nempatia;\ntolerância à frustração;\nautoconsolo.\nIndicadores positivos:\nprocura conforto;\naceita ajuda;\nrecupera após frustração;\ndemonstra curiosidade." },
  { number: 5, title: "Desenvolvimento Cognitivo", body: "Inclui:\natenção;\nmemória;\nresolução de problemas;\nraciocínio;\npermanência do objeto;\nfunções simbólicas;\nflexibilidade cognitiva.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n-- 6 of 13 --" },
  { number: 6, title: "Desenvolvimento da Linguagem", body: "Áreas a observar:\nLinguagem recetiva\ncompreensão;\nordens;\nconceitos;\nvocabulário.\nLinguagem expressiva\nvocabulário;\nestrutura frásica;\nnarrativa;\npragmática.\nComunicação\ncontacto ocular;\ngestos;\nreciprocidade;\natenção conjunta." },
  { number: 7, title: "Desenvolvimento Motor", body: "Motricidade global\nequilíbrio;\ncoordenação;\nmarcha;\ncorrida;\nsalto.\nMotricidade fina\npreensão;\ngrafomotricidade;\ncoordenação óculo-manual;\nmanipulação.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n-- 7 of 13 --" },
  { number: 8, title: "Desenvolvimento Social", body: "Avaliar:\ninteração com pares;\ninteração com adultos;\njogo simbólico;\nreciprocidade;\ncompetências pró-sociais;\nadaptação escolar." },
  { number: 9, title: "Funções Executivas", body: "Principais componentes:\nmemória de trabalho;\ncontrolo inibitório;\nflexibilidade cognitiva;\nplaneamento;\nmonitorização;\norganização." },
  { number: 10, title: "Autorregulação", body: "Inclui:\nregulação emocional;\nregulação fisiológica;\nregulação comportamental;\nregulação atencional.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n-- 8 of 13 --" },
  { number: 11, title: "Processamento Sensorial", body: "Áreas avaliadas:\ntátil;\nvestibular;\npropriocetivo;\nauditivo;\nvisual;\ngustativo;\nolfativo.\nObservar:\nhipersensibilidade;\nhipossensibilidade;\nprocura sensorial;\nevitamento." },
  { number: 12, title: "Vinculação", body: "A qualidade das relações precoces influencia profundamente o desenvolvimento emocional e social da\ncriança.\nNa avaliação clínica devem ser observados:\nprocura de proximidade;\nutilização do adulto como base segura;\ncapacidade de consolação;\nreciprocidade;\nresposta à separação;\nresposta ao reencontro.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n-- 9 of 13 --" },
  { number: 13, title: "Fatores de Risco", body: "Pré-natais\nprematuridade;\ninfeções;\nconsumo de substâncias;\ncomplicações obstétricas.\nPerinatais\nhipóxia;\nbaixo peso;\ninternamento neonatal.\nPós-natais\nnegligência;\ntrauma;\ninstitucionalização;\ndoença crónica;\npobreza extrema." },
  { number: 14, title: "Red Flags", body: "Linguagem\nausência de balbucio;\nausência de palavras;\nperda de linguagem;\nausência de intenção comunicativa.\nSocialização\nausência de contacto ocular;\nausência de atenção conjunta;\nreduzida reciprocidade social.\nMotricidade\natraso significativo;\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nassimetrias persistentes;\nregressão.\nComportamento\nbirras muito intensas e persistentes;\nagressividade grave;\nautoagressão;\nrigidez marcada.\nSensorial\nreações extremas a sons, texturas ou luz;\nprocura sensorial intensa." },
  { number: 15, title: "Formulação Clínica", body: "O modelo PICCA organiza a informação clínica em cinco dimensões:\nMotivo da avaliação.\nHistória desenvolvimental e contexto familiar.\nIntegração dos resultados da avaliação.\nHipóteses clínicas e fatores predisponentes, precipitantes, perpetuantes e protetores.\nObjetivos terapêuticos e recomendações.\nEsta abordagem privilegia uma compreensão integrada da criança, considerando o seu funcionamento,\no contexto relacional e os fatores ambientais, em consonância com a perspetiva desenvolvimental e\nmultiaxial promovida pelo DC:0–5." },
  { number: 16, title: "Avaliação Multidisciplinar", body: "Profissionais frequentemente envolvidos:\nPsicólogo\nPediatra do Desenvolvimento\nNeuropediatra\nPedopsiquiatra\nTerapeuta da Fala\nTerapeuta Ocupacional\nFisioterapeuta\nNutricionista\n\n\n\n\n\n\n\n\n1.\n2.\n3.\n4.\n5.\n\n\n\n\n\n\n\n\nEducador de Infância" },
  { number: 17, title: "Instrumentos Recomendados", body: "Desenvolvimento\nGriffiths III\nBayley\nWPPSI\nWISC\nCognição\nRaven\nBANC\nAtenção e funções executivas\nConners\nBRIEF-P\nCHEXI\nEmoções\nASEBA\nSDQ\nRCMAS\nSCARED\nAutismo\nADOS-2\nCARS-2\nM-CHAT-R/F\nComportamento adaptativo\nVineland\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n-- 12 of 13 --" },
  { number: 18, title: "Checklists Clínicas", body: "Cada avaliação deverá incluir uma observação sistemática de:\ncontacto ocular;\ncomunicação verbal;\ncomunicação não verbal;\natenção conjunta;\njogo simbólico;\nreciprocidade social;\nexpressão emocional;\nautorregulação;\ncomportamento adaptativo;\nfunções executivas;\nprocessamento sensorial;\nmotricidade;\nautonomia;\ninteração com os cuidadores.\nConclusão\nA avaliação em idade pré-escolar deve privilegiar uma abordagem integrada, desenvolvimental e\ncentrada na criança e na família. A utilização de uma formulação clínica estruturada permite\ncompreender não apenas a presença de sintomas, mas também os fatores biológicos, relacionais e\ncontextuais que influenciam o desenvolvimento, orientando decisões diagnósticas e intervenções\nindividualizadas. Esta perspetiva é consistente com o enquadramento multiaxial e relacional promovido\npelo DC:0–5 e pelas orientações contemporâneas em saúde mental na primeira infância.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n-- 13 of 13 --" },
]
